### ISSUE TITLE
爱美剧 APP 哪里可以下载？😂

### ISSUE THREAD

**Issue by Miroxyz** [xiaotian1339/imjHOOK#1]

**Comment by xiaotian1339** [comment]
手机应用市场直接搜就出来了，图标是下面的，包名在代码里可以看到，很容易的一个逆向，可以当作练手用～

> 本项目仅供学习和研究，不得将本项目内容用于商业或者非法用途，否则，一切后果请自负。
图标如下：
![image](https://github.com/xiaotian1339/imjHOOK/assets/81060593/90c81a4f-6c7f-454f-a45a-6186ce258b84)
